/*!
	\file LLVMDynamicExecutionMetrics.h
	\author Andrew Kerr <arkerr@gatech.edu>
	\date May 31, 2011
*/

#ifndef OCELOT_EXECUTIVE_LLVMDYNAMICEXECUTIONMETRICS_H_INCLUDED
#define OCELOT_EXECUTIVE_LLVMDYNAMICEXECUTIONMETRICS_H_INCLUDED

#define METRIC_RUNTIME 0
#define METRIC_WARPSIZE 0
#define METRIC_ENTRYPOINT_LIVENESS 0
#define METRIC_LLVM_INSTRUCTIONCOUNTS 1

#endif

