# \file SConstruct
#
# \author Andrew Kerr <arkerr@gatech.edu>
# \date December 13, 2011
#
# \brief SConstruct for CUDA 4.1 examples to be used as a model for other tools
#

import os

if ARGUMENTS.get('mode', 'release') == 'debug':
	if not os.path.isdir('.debug_build'):
		os.mkdir('.debug_build')
	SConscript('SConscript', variant_dir='.debug_build',   duplicate=0, 
		exports={'mode':'debug'})
else:
	if not os.path.isdir('.release_build'):
		os.mkdir('.release_build')
	SConscript('SConscript', variant_dir='.release_build', duplicate=0,
		exports={'mode':'release'})


