################################################################################
#	\file   SConstruct
#	\author Gregory Diamos <gregory.diamos@gatech.edu>
#   \date   Tuesday March 8, 2011
#	\brief  The SCons master build script for Ocelot
################################################################################

import os
import inspect

# try to import an environment first
try:
  Import('env')
except:
  exec open("build/which.py")
  exec open("build/build-environment.py")
  env = Environment()
  
# on mac we have to tell the linker to link against the C++ library
if env['PLATFORM'] == "darwin":
  env.Append(LINKFLAGS = "-lstdc++")

# find all .cus & .cpps in the current directory
sources = []
directories = ['ocelot/ir/implementation', 
	'ocelot/analysis/implementation',
	'ocelot/api/implementation', 
	'ocelot/cal/implementation', 
	'ocelot/cuda/implementation', 
	'ocelot/executive/implementation', 
	'ocelot/ir/implementation', 
	'ocelot/parser/implementation', 
	'ocelot/trace/implementation', 
	'ocelot/translator/implementation', 
	'ocelot/util/implementation', 
	'hydrazine/implementation' ]
extensions = ['*.cpp', '*.lpp', '*.ypp']

for dir in directories:
  for ext in extensions:
    regexp = os.path.join(dir, ext)
    sources.extend(env.Glob(regexp))

# add the directory containing this file to the include path
this_file = inspect.currentframe().f_code.co_filename
this_dir = os.path.dirname(this_file)
env.Append(CPPPATH = [this_dir])

tester = env.Program('tester', sources)


