MC-GPU_v1.1.cu File Reference
MC-GPU_v1.1.cu File Reference
#include <MC-GPU_v1.1.h>
#include <MC-GPU_kernel_v1.1.cu>
Functions
int main (int argc, char **argv)
Main program to transport x rays in a 3D voxel geometry using the GPU.
void read_input (int argc, char **argv, int myID, unsigned long long int *total_histories, int *seed_input, int *gpu_id, int *num_threads_per_block, int *histories_per_thread, struct detector_struct *detector_data, unsigned long long int **image_ptr, int *image_bytes, struct source_struct *source_data, char *file_name_voxels, char file_name_materials[MAX_MATERIALS][250], char *file_name_output, int *num_projections, double *D_angle, double *angularROI_0, double *angularROI_1, double *initial_angle)
Read the input file given in the command line and return the significant data.
void trim_name (char *input_line, char *file_name)
Extract a file name from an input text line, trimming the initial blanks, trailing comment (#) and stopping at the first blank (the file name should not contain blanks).
char * fgets_trimmed (char *trimmed_line, int num, FILE *file_ptr)
Read a line of text and trim initial blancks and trailing comments (#).
void load_voxels (int myID, char *file_name_voxels, float *density_max, struct voxel_struct *voxel_data, float2 **voxel_mat_dens_ptr, unsigned int *voxel_mat_dens_bytes)
Read the voxel data and allocate the material and density matrix.
void load_material (int myID, char file_name_materials[MAX_MATERIALS][250], float *density_max, float *density_nominal, struct linear_interp *mfp_table_data, float2 **mfp_Woodcock_table_ptr, int *mfp_Woodcock_table_bytes, float3 **mfp_table_a_ptr, float3 **mfp_table_b_ptr, int *mfp_table_bytes, struct rayleigh_struct *rayleigh_table_ptr, struct compton_struct *compton_table_ptr)
Read the material input files and set the mean free paths and the "linear_interp" structures.
int report_host (char *file_name_output, struct detector_struct *detector_data, struct source_struct *source_data, unsigned long long int *image, double time_elapsed, unsigned long long int total_histories, int current_projection, int num_projections, double D_angle, double initial_angle, int myID, int numprocs)
Report the final results, from the host CPU.
void set_CT_trajectory (int myID, int num_projections, double D_angle, double angularROI_0, double angularROI_1, struct source_struct *source_data, struct detector_struct *detector_data)
Sets the CT trajectory: store in memory the source and detector rotations that are needed to calculate the multiple projections.
Detailed Description
Author:
Andreu Badal (Andreu.Badal-Soler@fda.hhs.gov)
Date:
2010/05/14 -- First version: 2009/03/17
Definition in file MC-GPU_v1.1.cu.
Function Documentation
char* fgets_trimmed (char * trimmed_line, int num, FILE * file_ptr)
Read a line of text and trim initial blancks and trailing comments (#).
Parameters:
[in] num Characters to read
[in] file_ptr Pointer to the input file stream
[out] trimmed_line Trimmed line from input file, skipping empty lines and comments
Definition at line 969 of file MC-GPU_v1.1.cu.
Referenced by read_input().
void load_material (int myID, char file_name_materials[MAX_MATERIALS][250], float * density_max, float * density_nominal, struct linear_interp * mfp_table_data, float2 ** mfp_Woodcock_table_ptr, int * mfp_Woodcock_table_bytes, float3 ** mfp_table_a_ptr, float3 ** mfp_table_b_ptr, int * mfp_table_bytes, struct rayleigh_struct * rayleigh_table_ptr, struct compton_struct * compton_table_ptr)
Read the material input files and set the mean free paths and the "linear_interp" structures.
Find the material nominal density. Set the Woodcock trick data.
Parameters:
[in] file_name_materials Array with the names of the material files.
[in] density_max maximum density in the geometry (needed to set Woodcock trick)
[out] density_nominal Array with the nominal density of the materials read
[out] mfp_table_data Constant values for the linear interpolation
[out] mfp_table_a_ptr First element for the linear interpolation.
[out] mfp_table_b_ptr Second element for the linear interpolation.
Definition at line 1166 of file MC-GPU_v1.1.cu.
References rayleigh_struct::aco, rayleigh_struct::bco, linear_interp::e0, compton_struct::fco, compton_struct::fj0, linear_interp::ide, rayleigh_struct::itlco, rayleigh_struct::ituco, MASTER_THREAD, compton_struct::noscco, linear_interp::num_values, rayleigh_struct::pco, rayleigh_struct::pmax, compton_struct::uico, and rayleigh_struct::xco.
Referenced by main().
void load_voxels (int myID, char * file_name_voxels, float * density_max, struct voxel_struct * voxel_data, float2 ** voxel_mat_dens_ptr, unsigned int * voxel_mat_dens_bytes)
Read the voxel data and allocate the material and density matrix.
Also find and report the maximum density defined in the geometry.
Parameters:
[in] file_name_voxels Name of the voxelized geometry file.
[out] density_max Array with the maximum density for each material in the voxels.
[out] voxel_data Pointer to a structure containing the voxel number and size.
[out] voxel_mat_dens_ptr Pointer to the vector with the voxel materials and densities.
Definition at line 1029 of file MC-GPU_v1.1.cu.
References voxel_struct::inv_voxel_size, MASTER_THREAD, MAX_MATERIALS, voxel_struct::num_voxels, and voxel_struct::size_bbox.
Referenced by main().
int main (int argc, char ** argv)
Main program to transport x rays in a 3D voxel geometry using the GPU.
This function reads the description of the simulation from an external file given in the command line. This input file defines the number of particles to simulate, the characteristics of the x-ray source and the detector, the number and spacing of the projections (if simulating a CT), the location of the material files containing the interaction mean free paths, and the location of the voxelized geometry file.
Author:
Andreu Badal
Date:
2010/03/19
Definition at line 170 of file MC-GPU_v1.1.cu.
References detector_struct::corner_min_rotated_to_Y, source_struct::cos_theta_low, source_struct::D_phi, detector_data_CONST, source_struct::direction, linear_interp::e0, source_struct::energy, linear_interp::ide, init_image_array_GPU(), detector_struct::inv_pixel_size_X, detector_struct::inv_pixel_size_Z, load_material(), load_voxels(), MASTER_THREAD, MAX_MATERIALS, mfp_table_data_CONST, detector_struct::num_pixels, linear_interp::num_values, source_struct::position, read_input(), report_host(), detector_struct::sdd, set_CT_trajectory(), source_data_CONST, track_particles(), and voxel_data_CONST.
void read_input (int argc, char ** argv, int myID, unsigned long long int * total_histories, int * seed_input, int * gpu_id, int * num_threads_per_block, int * histories_per_thread, struct detector_struct * detector_data, unsigned long long int ** image_ptr, int * image_bytes, struct source_struct * source_data, char * file_name_voxels, char file_name_materials[MAX_MATERIALS][250], char * file_name_output, int * num_projections, double * D_angle, double * angularROI_0, double * angularROI_1, double * initial_angle)
Read the input file given in the command line and return the significant data.
Example input file:
1000000 [Total number of histories to simulate] geometry.vox [Voxelized geometry file name] material.mat [Material data file name]
Parameters:
[in] argc Command line parameters
[in] argv Command line parameters: name opf input file
[out] total_histories Total number of particles to simulate
[out] seed_input Input random number generator seed
[out] num_threads_per_block Number of CUDA threads for each GPU block
[out] detector_data
[out] image
[out] source_data
[out] file_name_voxels
[out] file_name_materials
[out] file_name_output
!DeBuG!! Force square field for any phi!!
Definition at line 542 of file MC-GPU_v1.1.cu.
References detector_struct::corner_min_rotated_to_Y, source_struct::cos_theta_low, source_struct::D_cos_theta, source_struct::D_phi, source_struct::direction, source_struct::energy, fgets_trimmed(), detector_struct::height_Z, detector_struct::inv_pixel_size_X, detector_struct::inv_pixel_size_Z, MASTER_THREAD, source_struct::max_height_at_y1cm, detector_struct::num_pixels, source_struct::phi_low, source_struct::position, source_struct::rot_fan, detector_struct::rot_inv, detector_struct::rotation_flag, detector_struct::sdd, detector_struct::total_num_pixels, trim_name(), and detector_struct::width_X.
Referenced by main().
int report_host (char * file_name_output, struct detector_struct * detector_data, struct source_struct * source_data, unsigned long long int * image, double time_elapsed, unsigned long long int total_histories, int current_projection, int num_projections, double D_angle, double initial_angle, int myID, int numprocs)
Report the final results, from the host CPU.
Parameters:
[in] file_name_output File where tallied image is reported
[in] detector_data Detector description read from the input file (pointer to detector_struct)
[in] image Tallied image (in meV per pixel)
[in] time_elapsed Time elapsed during the main loop execution (in seconds)
[in] total_histories Total number of x-rays simulated
Definition at line 1543 of file MC-GPU_v1.1.cu.
References source_struct::energy, detector_struct::inv_pixel_size_X, detector_struct::inv_pixel_size_Z, detector_struct::num_pixels, and SCALE_eV.
Referenced by main().
void set_CT_trajectory (int myID, int num_projections, double D_angle, double angularROI_0, double angularROI_1, struct source_struct * source_data, struct detector_struct * detector_data)
Sets the CT trajectory: store in memory the source and detector rotations that are needed to calculate the multiple projections.
The first projection (0) was previously initialized in function "read_input".
ASSUMPTIONS: the CT scan plane must be perpendicular to the Z axis, ie, the initial direction of the particles must have w=0!
Definition at line 1650 of file MC-GPU_v1.1.cu.
References detector_struct::corner_min_rotated_to_Y, source_struct::direction, detector_struct::height_Z, MASTER_THREAD, source_struct::position, source_struct::rot_fan, detector_struct::rot_inv, detector_struct::sdd, and detector_struct::width_X.
Referenced by main().
void trim_name (char * input_line, char * file_name)
Extract a file name from an input text line, trimming the initial blanks, trailing comment (#) and stopping at the first blank (the file name should not contain blanks).
Parameters:
[in] input_line Input sentence with blanks and a trailing comment
[out] file_name Trimmed file name
Definition at line 941 of file MC-GPU_v1.1.cu.
Referenced by read_input().