# (c) 2007 The Board of Trustees of the University of Illinois.

include $(PARBOIL_ROOT)/common/mk/common.mk

SRCDIR_OBJS=main.o file.o
EXTRA_LIBS=-lm -lstdc++
EXTRA_CFLAGS=-ffast-math
EXTRA_CXXFLAGS=-ffast-math

LINK_MODE=C

all : $(BIN)

include $(PARBOIL_ROOT)/common/mk/rules.mk
