################################################################################
#
# Copyright 1993-2010 NVIDIA Corporation.  All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property and 
# proprietary rights in and to this software and related documentation. 
# Any use, reproduction, disclosure, or distribution of this software 
# and related documentation without an express license agreement from
# NVIDIA Corporation is strictly prohibited.
#
# Please refer to the applicable NVIDIA end user license agreement (EULA) 
# associated with this source code for terms and conditions that govern 
# your use of this NVIDIA software.
# 
#
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= simpleMultiGPU
# Cuda source files (compiled with cudacc)
CUFILES		:= simpleMultiGPU_kernel.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= simpleMultiGPU.cpp


################################################################################
# Rules and targets

include ../../common/common.mk
